version: '3.5'
services:

  app:
    build: .
    image: &app app
    restart: "no"
    env_file: &envfile
      - .env
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - worker

  worker:
    image: *app
    restart: "no"
    env_file: *envfile
    command: ["celery", "worker", "--app=taskrunner", "--concurrency=1", "--hostname=worker@%h", "--loglevel=INFO"]
    volumes:
      - ./app:/app
    depends_on:
      - broker
      - redis

  flower:
    image: *app
    restart: "no"
    env_file: *envfile
    command: ["flower", "--app=taskrunner", "--port=5555", "--broker=${FLOWER_BROKER}"]
    ports:
      - "5555:5555"
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - broker

  broker:
    image: rabbitmq:3
    env_file: *envfile
    ports:
      - "5672:5672"

  redis:
    image: redis
    ports:
      - "6379:6379"
